export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const CLEAN_USER_BY_ID = "CLEAN_USER_BY_ID";
export const ADMI_LOGIN = "ADMI_LOGIN";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_ADMI = "GET_USER_BY_ADMI";
export const CREATE_USER = "CREATE_USER";

//filtros
export const FILTER_BY_SOCIAL_MEDIA = "FILTER_BY_SOCIAL_MEDIA";
export const FILTER_BY_STATE = "FILTER_BY_STATE";
export const SEARCH_BY_CONTACT = "SEARCH_BY_CONTACT";
export const CLEAN_FILTERS = "CLEAN_FILTERS";
export const FILTER_BY_USER = "FILTER_BY_USER";
export const FILTER_BY_PRIVILEGE_USER = "FILTER_BY_PRIVILEGE_USER";
export const FILTER_BY_ACTIVE_USER = "FILTER_BY_ACTIVE_USER";

//mensajes recibidos
export const GET_ALL_MESSAGES_RECIVED = "GET_ALL_MESSAGES_RECIVED";
export const GET_MESSAGE_RECIVED_BY_ID = "GET_MESSAGE_RECIVED_BY_ID";
export const UPDATE_ACTIVE_MESSAGE_RECEIVED = "UPDATE_ACTIVE_MESSAGE_RECEIVED";
export const UPDATE_STATE_TO_READ_MESSAGE_RECEIVED =
  "UPDATE_STATE_TO_READ_MESSAGE_RECEIVED";
export const UPDATE_STATE_TO_ANSWERED_MESSAGE_RECEIVED =
  "UPDATE_STATE_TO_ANSWERED_MESSAGE_RECEIVED";
export const DESACTIVATE_ALL_MESSAGES_RECEIVED =
  "DESACTIVATE_ALL_MESSAGES_RECEIVED";
export const SET_ACTIVE_MESSAGE = "SET_ACTIVE_MESSAGE";
export const SET_UPLOAD_FILE = "SET_UPLOAD_FILE";
export const UPDATE_ARCHIVED_MESSAGE_RECEIVED =
  "UPDATE_ARCHIVED_MESSAGE_RECEIVED";

//mensajes enviados
export const CREATE_MESSAGE_SEND = "CREATE_MESSAGE_SEND";
export const GET_ALL_MESSAGES_SENT = "GET_ALL_MESSAGES_SENT";

//busnisess
export const GET_BUSINESS_BY_ID = "GET_BUSINESS_BY_ID";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const LOGIN_BUSINESS = "LOGIN_BUSINESS";
export const LOGOUT_BUSINESS = "LOGOUT_BUSINESS";

//contactos
export const GET_CONTACT_BY_ID = "GET_CONTACT_BY_ID";
export const GET_CONTACT_BY_MESSAGE_RECEIVED =
  "GET_CONTACT_BY_MESSAGE_RECEIVED";
export const CLEAR_CONTACT = "CLEAR_CONTACT";

//redes sociales
export const GET_ALL_SOCIAL_MEDIA_BY_BUSINESS = "GET_SOCIAL_MEDIA_BY_BUSINESS";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const UPDATE_AUTOMATIC_RESPONSE = "UPDATE_AUTOMATIC_RESPONSE";
export const DELETE_AUTOMATIC_RESPONSE = "DELETE_AUTOMATIC_RESPONSE";

//socket
export const NEW_MESSAGE_RECEIVED = "NEW_MESSAGE_RECEIVED";
export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_ERROR = "SOCKET_ERROR";
//mios:
export const ADD_NEW_MESSAGE_RECEIVED = "ADD_NEW_MESSAGE_RECEIVED";
export const ADD_NEW_MESSAGE_SENT = "ADD_NEW_MESSAGE_SENT";

//auth:
export const AUTH_BUSINESS_BY_ALL_SOCIAL_MEDIA =
  "AUTH_BUSINESS_BY_ALL_SOCIAL_MEDIA";
export const POST_CODE_TO_AUTH_MELI = "POST_CODE_TO_AUTH_MELI";
export const POST_CODE_TO_AUTH_MELI_ERROR = "POST_CODE_TO_AUTH_MELI_ERROR";
